name: "Autocreate PR"
description: "Set a PR to auto-create"

branding:
  color: yellow
  icon: git-pull-request

runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash

    - run: create_pr.sh
      shell: bash


