name: "Autocreate PR"
description: "Set a Pull Request to auto-create"

branding:
  color: yellow
  icon: git-pull-request

inputs:
   automerge:
     description: "Set the PR with auto-merge"
     required: false
     default: false
   enable_to_all:
     description: "Allow any one to use the action"
     required: false
     default: false


runs:
  using: "composite"
  steps:
    - name: Create PR
      run: $GITHUB_ACTION_PATH/create_pr.sh
      shell: bash
      env:
        INPUT_AUTOMERGE: ${{ inputs.automerge }}


