name: "Create Pull Request"
description: "Create Pull Request with a flag to auto_merge"

branding:
  color: yellow
  icon: git-pull-request

inputs:
   auto_merge:
     description: "Set the Pull Request with auto-merge"
     required: false
     default: "false"
   draft:
     description: "Set the Pull Request to draft"
     required: false
     default: "false"
   merge_method:
     description: "Set the Pull Request to draft"
     required: false
     default: "MERGE"


runs:
  using: "composite"
  steps:
#    - name: Set up Python
#      uses: actions/setup-python@v4
#      with:
#        python-version: "3.x"
#        cache: 'pip'

#    - name: Installing Python dependencies
#      run: pip install -r $GITHUB_ACTION_PATH/requirements.txt
#      shell: bash

    - name: Create Pull Resquest
      run: python $GITHUB_ACTION_PATH/autocreate.py
      shell: bash
      env:
        INPUT_AUTO_MERGE: ${{ inputs.auto_merge }}
        INPUT_DRAFT: ${{ inputs.draft }}
        INPUT_MERGE_METHOD: ${{ inputs.merge_method }}
