name: "Autocreate PR"
description: "Set a PR to auto-create"

branding:
  color: yellow
  icon: git-pull-request

inputs:
  personal_access_token:
    description: "Github Personal access token"
    required: true

  automerge:
    description: "Set the Pull Request to auto-merge"
    required: false
    default: 'false'
runs:
  using: "docker"
  image: "Dockerfile"
