name: "Create Pull Request"
description: "Create Pull Request with a flag to automerge"

branding:
  color: yellow
  icon: git-pull-request

inputs:
   automerge:
     description: "Set the Pull Request with auto-merge"
     required: false
     default: "false"
   draft:
     description: "Set the Pull Request to draft"
     required: false
     default: "false"


runs:
  using: "composite"
  steps:
    - name: Installing dependencies
      run: pip install -r $GITHUB_ACTION_PATH/requirements.txt
      shell: bash

    - name: Create Pull Resquest
      run: python $GITHUB_ACTION_PATH/autocreate.py
      shell: bash
      env:
        INPUT_AUTOMERGE: ${{ inputs.automerge }}
        INPUT_DRAFT: ${{ inputs.draft }}
