name: "Autocreate PR"
description: "Set a Pull Request to auto-create"

branding:
  color: yellow
  icon: git-pull-request

inputs:
   automerge:
     description: "Set the PR with auto-merge"
     required: false
     default: false


runs:
  using: "composite"
  steps:
    - name: Define GitHub Path
      run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash

    - name: Set inputs
      run: echo "INPUT_AUTOMERGE=${{ inputs.automerge }}" >> $GITHUB_ENV
      shell: bash

    - name: Create PR
      run: create_pr.sh
      shell: bash


