name: Autocreate PR

on:
  push:
    branches-ignore:
      - master

jobs:
  creating-PR:
    name: Create PR
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Creating PR
        uses: heitorpolidoro/autocreate-pr@master
        with:
          personal_access_token: ${{ secrets.PAT }}