name: Create Pull Request

on:
  create:

jobs:
  create-PR:
    name: Create Pull Request
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Creating Pull Request
        uses: heitorpolidoro/autocreate-pr@v2.1.0
        with:
          auto_merge: true

        env:
          heitorpolidoro: ${{ secrets.HEITORPOLIDORO_PAT }}
