name: Create Pull Request

on:
  create:
  push:
jobs:
  create-PR:
    name: Create Pull Request
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Creating Pull Request
        uses: heitorpolidoro/autocreate-pr@enable-to-all3
        with:
          automerge: true
          enable-to-all: true
