name: Create Pull Request

on:
  create:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - master
jobs:
  create-PR:
    name: Create Pull Request
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Creating Pull Request
        uses: heitorpolidoro/autocreate-pr@logging
        with:
          auto_merge: true
          merge_method: SQUASH

        env:
          heitorpolidoro: ${{ secrets.HEITORPOLIDORO_PAT }}
