name: Push Branch

on:
  push:
    branches-ignore:
      - master

jobs:
  creating-PR:
    name: Create Pull Request
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Creating Pull Request
        uses: heitorpolidoro/autocreate-pr@CU-864e2xznv_Sonar
        env:
          heitorpolidoro: ${{ secrets.HEITORPOLIDORO_PAT }}